apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-public-nas
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-00
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid
    volumeAttributes:
      server: 10.0.1.74
      share: /public-nas    #나스 스토리지 이름