apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-public-nas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: pv-public-nas
  storageClassName: sc-00