apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec: # specification for deployment resource
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template: # blueprint for Pod
    metadata:
      labels:
        app: wordpress
    spec: # specification for Pod
      containers:
      - name: wordpress
        image: 2be61e1b-kr1-registry.container.nhncloud.com/dpgtb-cr/wordpress:8.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wp-public-nas
          mountPath: "/var/www/html"
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: database_url
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: password
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DEBUG
          value: "1"
      volumes:
        - name: wp-public-nas
          persistentVolumeClaim:
            claimName: wpc-public-nas
      imagePullSecrets:
      - name: wpimage-secret
